### ISSUE TITLE
Ostersonntag in DE

### ISSUE THREAD

**Issue by ickbinhier** [checkdomain/Holiday#31]
der Ostersonntag ist laut https://de.wikipedia.org/wiki/Gesetzliche_Feiertage_in_Deutschland nur in Brandenburg und Hessen gesetzlicher Feiertag.

Soll / Kann ich das anpassen?

**Comment by ickbinhier** [comment]
Pfingst-Sonntag hat das gleiche Problem....

**Comment by FlorianKoerner** [comment]
Kannst du gerne machen.

**Comment by ickbinhier** [comment]
#34
